require("prototypes.entity.transport-belt-4")
require("prototypes.entity.underground-belt-4")
require("prototypes.entity.splitter-4")
require("prototypes.entity.transport-belt-5")
require("prototypes.entity.underground-belt-5")
require("prototypes.entity.splitter-5")
require("prototypes.entity.transport-belt-6")
require("prototypes.entity.underground-belt-6")
require("prototypes.entity.splitter-6")

require("prototypes.item.transport-belt-4")
require("prototypes.item.underground-belt-4")
require("prototypes.item.splitter-4")
require("prototypes.item.transport-belt-5")
require("prototypes.item.underground-belt-5")
require("prototypes.item.splitter-5")
require("prototypes.item.transport-belt-6")
require("prototypes.item.underground-belt-6")
require("prototypes.item.splitter-6")

require("prototypes.recipe.transport-belt-4")
require("prototypes.recipe.underground-belt-4")
require("prototypes.recipe.splitter-4")
require("prototypes.recipe.transport-belt-5")
require("prototypes.recipe.underground-belt-5")
require("prototypes.recipe.splitter-5")
require("prototypes.recipe.transport-belt-6")
require("prototypes.recipe.underground-belt-6")
require("prototypes.recipe.splitter-6")

require("prototypes.technology.logistics-4")
require("prototypes.technology.logistics-5")
require("prototypes.technology.logistics-6")